# Generated by Django 4.1.3 on 2022-12-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'verbose_name_plural': 'Adicionais'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='opcoes',
            options={'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name_plural': 'Produtos'},
        ),
    ]
